global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']       # Put your Public IP 

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']        # Put your Public Ip

# optional: node_exporter if you add it later
#  - job_name: 'node_exporter'
#    static_configs:
#      - targets: ['node-exporter:9100']    # Put your Public IP

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']          # Put your Public IP
